name: CI (backend)

on:
  push:
    branches:
      - master
      - 'feature/*'
    paths:
      - '.github/workflows/ci-backend.yml'
      - 'backend/ecosystem.config.js'
      - 'backend/eslint.config.mjs'
      - 'backend/src/**.js'
      - 'backend/tests/**.js'
    # paths-ignore:
    #    - 'backend/scripts/**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend

    strategy:
      matrix:
        node-version: [ 18.x, 20.x, 22.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build --if-present

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Start Service (for Integration Tests)
        run: |
          npm run start:ci
          sleep 1
          echo "Waiting for service to be ready..."
          for i in {1..10}; do
            if curl -s http://localhost:3000/health; then
              echo "Service is up!"
              exit 0
            fi
            echo "Service not ready yet, retrying in 2s..."
            sleep 2
          done
          echo "Service failed to start in time."
          exit 1

      - name: Run Integration Tests
        run: npm run test:integration

      - name: Teardown Service
        run: npm run stop
