name: Frontend CI

on:
  push:
    branches:
      - master
      - 'feature/*'
    paths:
      - '.github/workflows/ci-frontend.yml'
      - 'frontend/public/**'
      - 'frontend/src/**'
      - 'frontend/tests/**'
  pull_request:
    branches:
      - master
      - 'feature/*'
    paths:
      - '.github/workflows/ci-frontend.yml'
      - 'frontend/public/**'
      - 'frontend/src/**'
      - 'frontend/tests/**'

env:
  VITE_PORT: 4173

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest
        run: npm run test

      # - name: Build project
      #   run: npm run build

      - name: Spin up services
        run: |
          docker compose build
          docker compose up -d
          echo "Waiting for service to be ready..."
          for i in {1..10}; do
            if curl -s http://localhost:3000/api/health; then
              echo "Service is up!"
              exit 0
            fi
            echo "Service not ready yet, retrying in 2s..."
            sleep 2
          done
          echo "Service failed to start in time."
          exit 1
        working-directory: .

      # - name: Spin up service
      #   run: npm run start:ci

      - name: Run Cypress tests
        run: npm run test:e2e:cypress

      - name: Run Playwright tests
        run: npm run test:e2e:playwright

      # - name: Run Lighthouse CI
      #   run: npm run test:lighthouse || echo "Lighthouse assertions failed"

      - name: Teardown services
        run: docker compose down
        working-directory: .

      # - name: Tear down API
      #   run: npm run stop
      #   working-directory: ./backend
